### ISSUE TITLE
Move to Jekyll

### ISSUE THREAD

**Issue by rjaltman** [IndigoBox/indigoBox-Website#6]
It would benefit, especially with the header insertion by JS (which doesn't help for SEO since projects and links would not be found by crawlers), that we use Jekyll to manage these things instead. 

This was a short issue, and basically said to me by @vkoves, actually.

**Comment by vkoves** [comment]
I will probably end up taking this on, but wanted to add some resources in case someone else would like to give it a shot. I use Jekyll on my personal site and have found it exceptionally useful in creating a feature rich website that is modular without a backend framework. With that said, some resources:

- To get a bit of an introduction, check out [Jekyll's Main Site](https://jekyllrb.com/)
- Jekyll has a good Jekyll cast regarding [Converting a Static Site to Jekyll](http://jekyll.tips/jekyll-casts/converting-a-static-site-to-jekyll/)

**Comment by vkoves** [comment]
I've started the basics of this. Ideally all of the `<head>` should be moved into Jekyll, and each HTML page should just contain pure content and no tags that are repeated in each file. However, per commit 04ab48d, the header is now imported using Jekyll, rather than being appended using jQuery, so that maintains modularity while improving SEO. I'll close this issue once the main indigoBox pages have been made into proper content only files.

**Comment by vkoves** [comment]
I've moved all the main pages (non project sites) over to the default layout, which is now modular and takes care of the `<head>` tag. See f98fe10. I'm closing this issue since now the site is basically fully moved over to Jekyll. If anyone finds additional improvements that should be made, feel free to reopen this issue and comment with them.
